fix(nav2_examples): use nav2_ros_common for node_utils.hpp
The node_utils.hpp header was moved from nav2_util to nav2_ros_common
as part of the ROS2 nav2 reorganization. This change updates the
example packages to:

1. Use the correct include path: nav2_ros_common/node_utils.hpp
   instead of nav2_util/node_utils.hpp
2. Add nav2_ros_common as a dependency in CMakeLists.txt and package.xml
   for all example packages (example_planner, example_controller,
   example_costmap_layer)

This fixes the CI build error:
  fatal error: nav2_util/node_utils.hpp: No such file or directory

Signed-off-by: niveshdandyan <niveshdandyan@users.noreply.github.com>